<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="UnitTestDataProvider" duration-ms="175" started-at="2016-10-13T06:54:27Z" finished-at="2016-10-13T06:54:27Z">
    <groups>
    </groups>
    <test name="DataProviderTests" duration-ms="175" started-at="2016-10-13T06:54:27Z" finished-at="2016-10-13T06:54:27Z">
      <class name="unitTests.TestDataProviderTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:unitTests.TestDataProviderTests@15975490]" name="setUp" is-config="true" duration-ms="82" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testEmail()[pri:0, instance:unitTests.TestDataProviderTests@15975490]" name="testEmail" duration-ms="3" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Incorrect value of email retrieved expected [parinit3@outlook.com] but found [parinit14@abc.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Incorrect value of email retrieved expected [parinit3@outlook.com] but found [parinit14@abc.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at unitTests.TestDataProviderTests.testEmail(TestDataProviderTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEmail -->
        <test-method status="PASS" signature="testProductID()[pri:0, instance:unitTests.TestDataProviderTests@15975490]" name="testProductID" duration-ms="3" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductID -->
        <test-method status="PASS" signature="testUsernaame()[pri:0, instance:unitTests.TestDataProviderTests@15975490]" name="testUsernaame" duration-ms="1" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUsernaame -->
      </class> <!-- unitTests.TestDataProviderTests -->
      <class name="unitTests.RunConfigurationTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:unitTests.RunConfigurationTests@47f6473]" name="setUp" is-config="true" duration-ms="13" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testIEServerPath()[pri:0, instance:unitTests.RunConfigurationTests@47f6473]" name="testIEServerPath" duration-ms="11" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIEServerPath -->
        <test-method status="PASS" signature="testLoadTimeout()[pri:0, instance:unitTests.RunConfigurationTests@47f6473]" name="testLoadTimeout" duration-ms="3" started-at="2016-10-13T12:24:27Z" finished-at="2016-10-13T12:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoadTimeout -->
      </class> <!-- unitTests.RunConfigurationTests -->
    </test> <!-- DataProviderTests -->
  </suite> <!-- UnitTestDataProvider -->
</testng-results>
